// Central media helpers.
//
// Optimized images live in /public/media/opt as .webp (generated by
// scripts/optimize-images.mjs). blurData maps an optimized public path to a
// tiny base64 LQIP so <Image> can render placeholder="blur" without layout shift.
import blurData from './blur-data.json';

const blurMap = blurData as Record<string, string>;

/**
 * Returns the blurDataURL for an optimized image path, or undefined if none.
 * Pass the same string you use as the Image `src` (e.g. '/media/opt/IMG_4403_2.webp').
 */
export function blurFor(src: string): string | undefined {
  return blurMap[src];
}

/**
 * Convenience: props to spread onto a next/image <Image> so it always gets a
 * blur placeholder when one is available.
 *   <Image src={img.src} {...blurProps(img.src)} ... />
 */
export function blurProps(src: string):
  | { placeholder: 'blur'; blurDataURL: string }
  | { placeholder?: undefined } {
  const b = blurMap[src];
  return b ? { placeholder: 'blur', blurDataURL: b } : {};
}
